const video=(id,time=0)=>`https://www.youtube.com/watch?v=${id}&t=${time}s`;
const blocks=[
{id:'start',n:'01',title:'Стартовая разминка',sub:'Плавно, без длительных остановок',rounds:1,items:[
{name:'Подкручивание таза лёжа',reps:'8–10 раз',muscles:'Таз и поясница',text:'Ляг на спину, согни колени. На выдохе мягко подкрути таз и приблизь поясницу к полу. Таз не поднимай как в мосте.',v:['VZ3f0pSTObM',20,'0:20']},
{name:'Разворот грудного отдела у стены',reps:'5–6 раз на сторону',muscles:'Подвижность грудного отдела',text:'Поворачивай верхнюю часть корпуса, сохраняя таз неподвижным. Двигайся в комфортной амплитуде.',v:['HaDInlkF4_0',29,'0:29']}]},
{id:'circuit',n:'02',title:'Круговой разогрев',sub:'Знакомый блок для повышения пульса',rounds:3,note:'10–20 с между упражнениями · 30–45 с между кругами · 60–90 с после третьего круга. Резинки лёгкие, без работы до отказа.',items:[
{name:'«Китайское» приседание с подъёмом таза и разворотом',reps:'8 раз на сторону',muscles:'Ноги и подвижность корпуса',text:'Опустись в приседание, затем подними таз, частично выпрямляя ноги, и раскрой корпус с подъёмом руки. Чередуй стороны. Выполняй без резинки.',detail:'Колени направляй по линии носков. Глубина — комфортная; касаться пола любой ценой не нужно. Прекрати движение, если возникает боль в колене.',v:['v3rlWAQRSVk',0,'0:00']},
{name:'Подъём колена с лёгкой резинкой',reps:'10 раз каждой ногой',muscles:'Сгибатели бедра и корпус',text:'Резинка проходит вокруг стоп. Поднимай колено, удерживая корпус ровно. Не отклоняйся назад. Для равновесия можно придерживаться за стену.',v:['TONqRYxVuW4',0,'0:00']},
{name:'Разведение резинки над головой',reps:'12 раз',muscles:'Плечевой пояс',text:'Возьми лёгкую длинную резинку широким хватом. Подними руки и плавно разведи их, как в ролике. Не прогибай поясницу и не проталкивай руки назад через дискомфорт в плечах.',v:['y4qQOmIxxhI',0,'0:00']},
{name:'Подъём и опускание вытянутых ног лёжа',reps:'6–10 раз',muscles:'Пресс и сгибатели бедра',text:'Подними ноги и медленно опускай только до той высоты, на которой сохраняешь контроль поясницы. Не обязательно опускать пятки до пола.',detail:'Если поясница начинает прогибаться или напрягаться, уменьши амплитуду либо немного согни колени. Заверши подход до потери контроля.',v:['SuIxXbKnwx4',8,'0:08']}]},
{id:'legs1',n:'03',title:'Ноги · пара 1',sub:'Задняя и внутренняя поверхность бедра',rounds:2,items:[
{name:'Румынская тяга с длинной резинкой',reps:'10–15 раз',muscles:'Ягодицы и задняя поверхность бедра',text:'Наступи на резинку обеими стопами и удерживай её руками. Слегка согни колени. Отводи таз назад, наклоняя корпус, затем выпрямись за счёт движения таза вперёд.',detail:'Спина сохраняет естественное положение, руки идут близко к ногам. Опускайся за 2–3 секунды. Не превращай движение в приседание.',v:['9aLdnLtIBhY',4,'0:04']},
{name:'Приведение ноги перед собой с резинкой',reps:'12–20 раз на сторону',muscles:'Внутренняя поверхность бедра',text:'Надень короткую лёгкую петлю чуть выше лодыжек. Придерживайся за стену. Приподними рабочую стопу и проведи её перед опорной ногой поперёк тела, растягивая петлю. Пауза 1 секунду, затем плавно вернись.',detail:'Стоишь на левой ноге — правую ведёшь перед ней влево. Корпус и таз не разворачивай, опорную стопу не скручивай. Сопротивление должно увеличиваться при перекрёстном движении. Простое сведение широко расставленных ног резинка облегчает. При боли в любом колене прекрати упражнение.',extra:'Начни с 12 повторений. Дойдя до 20 в обоих подходах на двух тренировках подряд, возьми чуть более тугую петлю и вернись к 12. Сохраняй амплитуду.',v:['_KJlIdLgjUs',1,'0:01']}]},
{id:'legs2',n:'04',title:'Ноги · пара 2',sub:'Ягодицы и передняя поверхность бедра',rounds:2,items:[
{name:'Ягодичный мост',reps:'12–20 раз',muscles:'Ягодицы',text:'Ляг на спину, согни колени, стопы примерно на ширине таза. Короткая резинка — выше колен. Подними таз, задержись на 1–2 секунды и плавно опустись.',detail:'Колени удерживай по линии стоп. Не добавляй отдельное разведение коленей в каждом повторении. Не прогибай поясницу ради большей высоты.',extra:'Когда станет легко, добавь длинную резинку поперёк таза, удерживая её руками у пола.',v:['kOAy8BGdxBc',523,'8:43'],links:[['zMZWyURC6tw',18,'Как установить длинную резинку · 0:18'],['zMZWyURC6tw',38,'Мост с длинной резинкой · 0:38']]},
{name:'Жим двумя ногами лёжа',reps:'10–15 раз',muscles:'Квадрицепсы и ягодицы',text:'Длинная резинка проходит поперёк середины обеих стоп; удерживай её руками. Из положения с согнутыми коленями плавно выпрямляй ноги вверх и немного вперёд, затем возвращай.',detail:'Голова остаётся на коврике. Не подтягивай колени настолько глубоко, чтобы таз отрывался от пола. Не выпрямляй колени рывком. Резинка держится на середине стоп, не на пальцах. Начни с лёгкой и оставляй 3 повторения в запасе.',v:['T4pRmVd-kNk',0,'0:00–0:02 · внизу экрана']}]},
{id:'legs3',n:'05',title:'Ноги · пара 3',sub:'Боковая часть ягодиц и устойчивость корпуса',rounds:2,items:[
{name:'Подъём верхней ноги лёжа на боку',reps:'12–20 раз на сторону',muscles:'Средняя и малая ягодичные',text:'Короткая резинка — выше колен. Нижнюю ногу можно согнуть, верхнюю держи прямой. Поднимай верхнюю ногу, не разворачивая таз назад.',detail:'Носок направляй вперёд, не к потолку. Большая высота не нужна — важнее контроль. Здесь поднимается верхняя нога и работает боковая часть ягодиц.',v:['OjNw-QDLJJQ',0,'0:00']},
{key:'bird-dog',name:'«Птица-собака»: противоположные рука и нога',reps:'6–8 раз на сторону · пауза 3 секунды',muscles:'Корпус, ягодицы и плечевой пояс',text:'Встань на четвереньки: ладони под плечами, колени под тазом. Одновременно вытяни одну руку вперёд, противоположную ногу назад — примерно до линии корпуса. Задержись на 3 секунды, вернись и поменяй сторону. Выполняй без резинки.',detail:'Тянись в длину, а не вверх. Таз не разворачивай, поясницу не прогибай, дыши спокойно. Это упражнение на совместную работу конечностей и устойчивость корпуса, без отдельной нагрузки на икры. Если коленям неприятно от давления, сложи край коврика; при сохраняющейся боли прекрати упражнение.',extra:'Начни с 6 повторений на сторону с паузой 3 секунды. Постепенно дойди до 8 повторений с паузой 5 секунд. Не увеличивай высоту подъёма и не стремись к отказу: здесь важен контроль.',v:['ZdAHe9_HeEw',8,'0:08']}]},
{id:'upper1',n:'06',title:'Верх · пара 1',sub:'Спина и грудь; руки помогают движению',rounds:2,items:[
{name:'Тяга резинки сидя к поясу',reps:'10–15 раз',muscles:'Спина и бицепс',text:'Сядь и немного согни колени. Резинка проходит вокруг середины стоп, пятки на полу. Тяни локти назад вдоль корпуса, направляя руки к поясу.',detail:'Не раскачивайся и не поднимай плечи к ушам. Возвращай руки медленно. Следи, чтобы резинка не соскальзывала со стоп.',v:['mnP10HI18uI',5,'0:05']},
{name:'Жим резинки от груди стоя',reps:'10–15 раз',muscles:'Грудь, трицепс, передняя часть плеч',text:'Длинная резинка проходит за верхней частью спины, ниже подмышек. Возьми её возле груди, одну стопу поставь немного впереди. Выжимай руки перед собой и плавно возвращай.',detail:'Локти немного ниже уровня плеч, запястья ровно. Не прогибай поясницу. Крепление не требуется.',v:['BO6QMnJzJ4g',8,'0:08']}]},
{id:'upper2',n:'07',title:'Верх · пара 2',sub:'Плечи и трицепс',rounds:2,items:[
{key:'mini-row',name:'Тяга короткой резинки одной рукой к груди',reps:'12–15 раз на руку',muscles:'Плечи, верх спины; помогает бицепс',text:'Одной рукой удерживай нижнюю часть короткой петли перед тазом, другой возьми верхнюю часть. Плавно тяни рабочую кисть вверх вдоль корпуса к нижней части груди, направляя локоть в сторону. Медленно опускай. Поменяй руки.',detail:'Используй лёгкую короткую резинку, как в ролике. Нижняя рука остаётся неподвижной. В нашей версии локоть не поднимай выше плеча и не тяни кисть к подбородку. Запястье держи ровно, плечо не подтягивай к уху. При защемлении или боли в плече остановись.',extra:'Оставляй 2–3 повторения в запасе. Когда оба подхода по 15 раз получаются уверенно на двух тренировках подряд, немного увеличь сопротивление и вернись к 12. Длинная резинка под стопами не нужна.',v:['DrARH_4OyPE',5,'0:05–0:08']},
{name:'Разгибание одной руки вверх',reps:'10–15 раз на руку',muscles:'Трицепс',text:'Одной рукой удерживай нижнюю часть резинки перед корпусом. Рабочую руку подними, согнув локоть, как в ролике. Выпрямляй её вверх и плавно возвращай.',detail:'Плечо и локоть сохраняй примерно на месте. Не прогибай поясницу.',v:['rlJ2OHDUc9k',0,'0:00']}]},
{id:'finish',n:'08',title:'Завершение',sub:'2–3 минуты в спокойном темпе',rounds:1,items:[
{key:'hip-flexor',name:'Растяжка сгибателя бедра с колена',reps:'20–30 секунд на сторону',muscles:'Передняя часть тазобедренного сустава',text:'Поставь одно колено на коврик, другую стопу впереди. Мягко подкрути таз, слегка напряги ягодицу задней ноги и немного перенеси таз вперёд. Задержись в комфортном натяжении, затем смени сторону.',detail:'Не прогибай поясницу и не уходи в глубокий выпад. Под опорное колено можно сложить край коврика. Если давление на колено вызывает боль, пропусти эту растяжку. В видео показана настройка положения; удерживай его спокойно, без пружинящих движений.',v:['H0s-v9cNSxg',28,'0:28']},
{name:'Подтягивание бёдер к животу лёжа',reps:'20–30 секунд',muscles:'Мягкое расслабление',text:'Голову оставь на коврике. Обхвати ноги за бёдра под коленями и мягко приблизь к животу, без давления на коленные суставы.',detail:'В ролике похожий вариант. Здесь используем захват за бёдра и оставляем голову внизу.',v:['GMzQkdd1AvI',19,'0:19']},
{name:'Спокойное дыхание',reps:'5 вдохов и длинных выдохов',muscles:'Восстановление дыхания',text:'Ляг удобно на спину, расслабь плечи. Дыши спокойно, без задержек и усилия.'}]}];
const $=s=>document.querySelector(s);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=new Date().toLocaleDateString('en-CA');
const storeKey='band-workout-v1';let checks={};
try{const saved=JSON.parse(localStorage.getItem(storeKey));if(saved?.day===today)checks=saved.checks??{};}catch{}
for(const key of Object.keys(checks)){if(/^(legs3-1-|upper2-0-|finish-0-)/.test(key))delete checks[key];}
const pairRules='<section class="pair-rules"><h2>Как выполнять силовые пары</h2><p>Первое упражнение → <strong>30–45 с отдыха</strong> → второе упражнение → <strong>60–90 с отдыха</strong>. Повтори пару ещё раз, затем переходи к следующей.</p><p>В односторонних упражнениях сначала выполни обе стороны. Между ними — 15–20 с. Одна отметка означает, что обе стороны выполнены.</p></section>';
const play='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 5v14l12-7z"/></svg>';
$('#workout').innerHTML=blocks.map((b,bi)=>(bi===2?pairRules:'')+`<section class="workout-block" id="${b.id}"><div class="block-heading"><span class="block-number">${b.n}</span><div><h2>${b.title}</h2><p>${b.sub}</p></div><span class="round-tag">${b.rounds} ${b.rounds===1?'круг':'круга'}</span></div>${b.note?`<p class="block-note">${b.note}</p>`:''}<div class="cards">${b.items.map((e,ei)=>`<article class="exercise"><div class="exercise-top"><span class="exercise-index">${String(ei+1).padStart(2,'0')}</span><span class="muscles">${e.muscles}</span></div><h3>${e.name}</h3><p class="reps">${e.reps}</p><p class="technique">${e.text}</p>${e.detail||e.extra?`<details><summary>Техника${e.extra?' и прогрессия':''}</summary>${e.detail?`<p>${e.detail}</p>`:''}${e.extra?`<p>${e.extra}</p>`:''}</details>`:''}${e.v?`<a class="video" href="${video(e.v[0],e.v[1])}" target="_blank" rel="noopener noreferrer" aria-label="Видео: ${esc(e.name)}, ${e.v[2]}">${play} Видео · ${e.v[2]}</a>`:''}${(e.links??[]).map(l=>`<a class="extra-link" href="${video(l[0],l[1])}" target="_blank" rel="noopener noreferrer">${l[2]}</a>`).join('')}<div class="checks">${Array.from({length:b.rounds},(_,r)=>{let id=`${b.id}-${e.key??ei}-${r}`;return `<label class="check"><input type="checkbox" data-id="${id}" ${checks[id]?'checked':''} aria-label="${esc(e.name)}: ${b.rounds===1?'выполнено':'круг '+(r+1)}"><span>${b.rounds===1?'Готово':'Круг '+(r+1)}</span></label>`}).join('')}</div></article>`).join('')}</div></section>`).join('');
function updateProgress(){const inputs=[...document.querySelectorAll('.check input')];let count=inputs.filter(i=>i.checked).length;$('#progress').max=inputs.length;$('#progress').value=count;$('#progress-text').textContent=count===inputs.length?'Тренировка завершена ✓':`Сегодня: ${count} из ${inputs.length} отметок`;document.querySelectorAll('.exercise').forEach(el=>el.classList.toggle('completed',[...el.querySelectorAll('input')].every(i=>i.checked)));try{localStorage.setItem(storeKey,JSON.stringify({day:today,checks}));}catch{}}
document.querySelectorAll('.check input').forEach(i=>i.addEventListener('change',()=>{checks[i.dataset.id]=i.checked;updateProgress()}));
$('#reset').addEventListener('click',()=>{if(!Object.values(checks).some(Boolean)||confirm('Сбросить все отметки за сегодня?')){checks={};document.querySelectorAll('.check input').forEach(i=>i.checked=false);updateProgress()}});updateProgress();
let duration=60,remaining=60,end=0,running=false,interval=null;
function renderTimer(){let s=Math.max(0,Math.ceil(remaining));$('#timer-value').textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;$('#timer-toggle').textContent=running?'Пауза':s===0?'Ещё раз':'Старт';$('.timer').classList.toggle('done',s===0);document.querySelectorAll('[data-time]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.time)===duration?'true':'false'))}
function pauseTimer(){if(running)remaining=Math.max(0,(end-Date.now())/1000);running=false;clearInterval(interval);renderTimer()}
function selectDuration(s){pauseTimer();duration=s;remaining=s;$('#timer-status').textContent='Готов к старту';renderTimer()}
function tick(){remaining=Math.max(0,(end-Date.now())/1000);if(remaining===0){running=false;clearInterval(interval);$('#timer-status').textContent='Отдых закончен';if(navigator.vibrate)navigator.vibrate([120,80,120]);}renderTimer()}
function startTimer(){if(running)return;if(remaining<=0)remaining=duration;running=true;end=Date.now()+remaining*1000;$('#timer-status').textContent='Восстанавливай дыхание';interval=setInterval(tick,200);tick()}
document.querySelectorAll('[data-time]').forEach(b=>b.addEventListener('click',()=>selectDuration(Number(b.dataset.time))));$('#timer-toggle').addEventListener('click',()=>{if(running){pauseTimer();$('#timer-status').textContent='На паузе'}else startTimer()});$('#timer-reset').addEventListener('click',()=>selectDuration(duration));document.addEventListener('visibilitychange',()=>{if(!document.hidden&&running)tick()});renderTimer();
if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){document.querySelectorAll('.block-nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+e.target.id));}},{rootMargin:'-70px 0px -65% 0px',threshold:0});document.querySelectorAll('.workout-block').forEach(s=>observer.observe(s));}
const context=document.modelContext;
if(context?.registerTool){for(const tool of [{name:'get_workout_progress',description:'Read today’s checked workout rounds on this device.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({completed:$('#progress').value,total:$('#progress').max,checked:Object.keys(checks).filter(k=>checks[k])})},{name:'start_rest_timer',description:'Start the visible workout rest timer for 20, 45, 60 or 90 seconds.',inputSchema:{type:'object',properties:{seconds:{type:'integer',enum:[20,45,60,90]}},required:['seconds'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||![20,45,60,90].includes(input.seconds))throw Error('Choose 20, 45, 60 or 90 seconds');selectDuration(input.seconds);startTimer();return{running,duration}}}]){try{Promise.resolve(context.registerTool(tool)).catch(()=>{});}catch{}}}
